name: demo

on:
  push:
    branches:
      - main

  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  demo1:
    runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
